version: "3.9"
services:
  app:
    build: .
    container_name: padroes-de-entrevista-php
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
      - "9003:9003"
    environment:
      - XDEBUG_MODE=debug
      - XDEBUG_CONFIG=client_host=host.docker.internal client_port=9003
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - mvc-net

  webserver:
    image: nginx:latest
    container_name: padroes-de-entrevista-nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - mvc-net

networks:
  mvc-net:
    driver: bridge
